[tools]
node = "20.15.0"

[env]
_.path = ["./node_modules/.bin"]

[tasks.setup]
run = ["mise install", "corepack enable", "pnpm install --frozen-lockfile"]

[tasks.build]
run = "turbo run build"

[tasks.check]
run = "turbo run check:format check:lint check:type check:unused --continue"

[tasks.fix]
run = ["turbo run fix:lint", "turbo run fix:format"]

[tasks.test]
run = "turbo run test"
