packages:
  - packages/*
  - playgrounds/*

catalog:
  "@commitlint/cli": ^20.1.0
  "@commitlint/config-conventional": ^20.0.0
  "@commitlint/config-pnpm-scopes": ^20.1.0
  "@commitlint/types": ^20.0.0
  "@eslint/config-helpers": 0.4.2
  "@eslint/config-inspector": ^1.3.0
  "@eslint/core": ^0.17.0
  "@eslint/js": ^9.39.1
  "@next/eslint-plugin-next": ^16.0.1
  "@touchspot/prettier-config": ^3.0.3
  "@tsconfig/next": ^2.0.3
  "@tsconfig/node22": ^22.0.2
  "@tsconfig/strictest": ^2.0.7
  "@types/fs-extra": 11.0.4
  "@types/node": ^22.19.0
  "@types/react": ^19.2.2
  "@vitest/coverage-v8": ^4.0.7
  better-typescript-lib: ^2.12.0
  commitizen: ^4.3.1
  cz-git: ^1.12.0
  eslint: ^9.39.1
  eslint-config-prettier: ^10.1.8
  eslint-import-resolver-typescript: ^4.4.4
  eslint-plugin-better-tailwindcss: ^3.7.10
  eslint-plugin-check-file: ^3.3.1
  eslint-plugin-functional: ^9.0.2
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-no-relative-import-paths: ^1.6.1
  eslint-plugin-perfectionist: ^4.15.1
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: 7.0.1
  eslint-plugin-unicorn: ^62.0.0
  eslint-plugin-unused-imports: ^4.3.0
  globals: ^16.5.0
  husky: ^9.1.7
  jotai: ^2.15.1
  knip: ^5.67.1
  lint-staged: ^16.2.6
  next: ^16.0.1
  prettier: ^3.6.2
  react: ^19.2.0
  react-dom: ^19.2.0
  tailwindcss: ^4.1.16
  ts-patch: ^3.3.0
  turbo: ^2.6.0
  typescript: ^5.9.3
  typescript-eslint: ^8.46.3
  typescript-transform-paths: ^3.5.5
  vite-tsconfig-paths: ^5.1.4
  vitest: ^4.0.7
  zx: 8.8.5

catalogMode: strict

cleanupUnusedCatalogs: true

ignoredBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver

linkWorkspacePackages: true

peerDependencyRules:
  allowedVersions:
    typescript: "*"

publicHoistPattern:
  - "@typescript/*"

savePrefix: ""

strictPeerDependencies: true

updateConfig:
  ignoreDependencies:
    - "@types/node"
