packages:
  - tests/*

onlyBuiltDependencies:
  - esbuild
  - oxc-resolver
  - sharp
  - unrs-resolver

patchedDependencies:
  eslint-plugin-react-hooks: patches/eslint-plugin-react-hooks.patch

peerDependencyRules:
  allowedVersions:
    typescript: "*"

publicHoistPattern:
  - "@typescript/*"

strictPeerDependencies: true
