packages:
  - tests/*

onlyBuiltDependencies:
  - esbuild
  - oxc-resolver
  - sharp
  - unrs-resolver

peerDependencyRules:
  allowedVersions:
    typescript: "*"

publicHoistPattern:
  - "@typescript/*"

strictPeerDependencies: true

updateConfig:
  ignoreDependencies:
    - "@types/node"
